# Generated by Django 5.2.12 on 2026-03-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='gradcam',
            field=models.ImageField(blank=True, null=True, upload_to='gradcam/'),
        ),
    ]
