# Generated by Django 5.2.12 on 2026-03-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
