# Generated by Django 5.2.12 on 2026-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
