# Generated by Django 5.2.12 on 2026-03-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='gradcam',
        ),
        migrations.AddField(
            model_name='report',
            name='lime_image',
            field=models.ImageField(blank=True, null=True, upload_to='lime/'),
        ),
    ]
