# Generated by Django 5.2.12 on 2026-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_gradcam_report_lime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
