# Generated by Django 5.2.12 on 2026-04-11 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_confidence'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='report',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
